### PR TITLE
add dontreadme_file

### PR DESCRIPTION
**Pull request by g0r0ch**
Here is answer on your issue

### CODE REVIEW

**Review by g0r0kh — CHANGES_REQUESTED** [review]
Hi my dear.
Find your job good, but not perfect. So i recomend you to pay some attention communication via CLI

**Review by g0r0ch — COMMENTED** [review]
So, how about this job&

**Review by g0r0kh — CHANGES_REQUESTED** [review]
Hmm, it's better then before but not excellent as expected
try better

**Comment by g0r0ch** [comment]
khm

**Pull request merged**
